name: Extract Zips
on:
  push:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          chmod +x extractAllZips.sh
          ./extractAllZips.sh -d directory
